/** @type {import('tailwindcss').Config} */

module.exports = {
  prefix: "_",
  important: true, // Doing this to fix CSS cascade order (Tailwind classes win, but wm__base overrides its preflight styles)
  content: [
    "./layout/**/*.liquid",
    "./sections/**/*.liquid",
    "./snippets/**/*.liquid",
    "./templates/**/*.liquid",
    "./templates/customers/**/*.liquid",
  ],
  theme: {
    extend: {
      colors: {
        'brand-primary-700': '#0F2D64',
        'brand-primary-500': '#3D72F6',
        'brand-secondary-700': '#6C7275',
        'brand-background': '#F1F1F1',
        'brand-background-light': '#F7F8F9',
        'brand-border': '#DADEE2',
        'brand-light': '#ffffff',
        'brand-dark': '#000000'
      },
      fontFamily: {
        'heading-primary': 'var(--font-heading-family)',
        'heading-primary-italic': 'var(--font-heading-family-italic)',
        'body-condensed': 'var(--font-body-condensed)'
      },
      fontSize: {
        '7xl': ['80px', { lineHeight: 'auto' }],
        '6xl': ['72px', { lineHeight: 'auto' }],
        '5xl': ['62px', { lineHeight: 'auto' }],
        '4xl': ['49px', { lineHeight: '1.25' }],
        '3xl': ['38px', { lineHeight: 'auto' }],
        '2xl': ['24px', { lineHeight: 'auto' }],
        'xl': ['20px', { lineHeight: 'auto' }],
        'lg': ['16px', { lineHeight: 'auto' }],
        'base': ['14px', { lineHeight: 'auto' }],
        'sm': ['12px', { lineHeight: 'auto' }],
        'xs': ['10px', { lineHeight: 'auto' }],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease forwards',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: 0, transform: 'translateY(10px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        }
      }
    }
  },
  safeList: [
    '_text-xl',
    '_text-2xl',
    '_text-2.5xl',
    '_text-3xl',
    '_text-4xl',
    '_text-5xl',
    '_text-6xl',
    '_text-7xl',
    '_text-8xl',
    '_text-9xl',
    'md:_text-xl',
    'md:_text-2xl',
    'md:_text-2.5xl',
    'md:_text-3xl',
    'md:_text-4xl',
    'md:_text-5xl',
    'md:_text-6xl',
    'md:_text-7xl',
    'md:_text-8xl',
    'md:_text-9xl',
    '_text-left',
    '_text-center',
    '_text-right',
    'md:_text-left',
    'md:_text-center',
    'md:_text-right',
    'md:_items-start',
    'md:_items-center',
    'md:_items-end',
    'md:_justify-start',
    'md:_justify-center',
    'md:_justify-end',
    '_mb-0',
    '_mb-1',
    '_mb-2',
    '_mb-4',
    '_mb-6',
    '_mb-8',
    '_mb-12',
    '_mb-16',
    '_mb-20',
    '_mb-24',
    '_mb-28',
    '_mb-32',
    'md:_mb-0',
    'md:_mb-1',
    'md:_mb-2',
    'md:_mb-4',
    'md:_mb-6',
    'md:_mb-8',
    'md:_mb-12',
    'md:_mb-16',
    'md:_mb-20',
    'md:_mb-24',
    'md:_mb-28',
    'md:_mb-32',
    '_mt-0',
    '_mt-1',
    '_mt-2',
    '_mt-4',
    '_mt-6',
    '_mt-8',
    '_mt-12',
    '_mt-16',
    '_mt-20',
    '_mt-24',
    '_mt-28',
    '_mt-32',
    'md:_mt-0',
    'md:_mt-1',
    'md:_mt-2',
    'md:_mt-4',
    'md:_mt-6',
    'md:_mt-8',
    'md:_mt-12',
    'md:_mt-16',
    'md:_mt-20',
    'md:_mt-24',
    'md:_mt-28',
    'md:_mt-32',
    '_py-0',
    '_py-1',
    '_py-2',
    '_py-4',
    '_py-6',
    '_py-8',
    '_py-12',
    '_py-16',
    '_py-20',
    '_py-24',
    '_py-28',
    '_py-32',
    'md:_py-0',
    'md:_py-1',
    'md:_py-2',
    'md:_py-4',
    'md:_py-6',
    'md:_py-8',
    'md:_py-12',
    'md:_py-16',
    'md:_py-20',
    'md:_py-24',
    'md:_py-28',
    'md:_py-32'
  ],
  plugins: [],
};
